language: python
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: 3.8
    - python: 3.7
    - python: 3.6
    - python: 3.5
    - python: 2.7

install:
  - pip install -U pip
  - pip install -e .
  - pip install -U flake8

script:
  # Test run
  - cmdbikes --help
  - cmdbikes ls
  - cmdbikes show --help
  - cmdbikes show "Pl. Joanic, Barcelona" -n 3

  # Static analysis
  - flake8 --statistics --count
